name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
   PERL_USE_UNSAFE_INC: 0
   AUTHOR_TESTING: 1
   AUTOMATED_TESTING: 1
   RELEASE_TESTING: 1
   PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - name: Set up Perl
        run: |
          choco install strawberryperl
          #echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
          echo 'C:\strawberry\c\bin' >> $GITHUB_PATH
          echo 'C:\strawberry\perl\site\bin' >> $GITHUB_PATH
          echo 'C:\strawberry\perl\bin' >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -L https://cpanmin.us > cpanminus.pl
      - run: perl cpanminus.pl --notest --installdeps --with-develop --with-configure --verbose .
      - run: perl Makefile.PL
      - run: gmake
      - name: Run Tests
        run: prove -vbl t

  cygwin:
    runs-on: windows-latest

    steps:
      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
            packages: perl_base perl-ExtUtils-MakeMaker make gcc-g++ bash libcrypt-devel libcrypt0 libnsl

      - uses: actions/checkout@main
        with:
            submodules: recursive
      - shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
            perl -V
            cpan -T App::cpanminus
            cd $GITHUB_WORKSPACE;
            cpanm --verbose --notest --installdeps --with-configure --with-develop .
            perl Makefile.PL
            make -j3 -j3 test
